[tox]
envlist = py,qa
skip_missing_interpreters = True
isolated_build = true
minversion = 4.0.0

[testenv]
commands =
	coverage run -m pytest -v -r wsx
	coverage report
deps =
	mock
	pytest>=3.1
	pytest-cov
	build
	{toxinidir}/fx/plasmafx
	{toxinidir}/fx/plasmafx_plugin_cycle

[testenv:qa]
commands =
	check-manifest
	python -m build --no-isolation
	python -m build --no-isolation --outdir dist fx/plasmafx
	python -m build --no-isolation --outdir dist fx/plasmafx_plugin_cycle
	python -m twine check dist/*
dependency_groups =
	dev
